version: '3.8'

services:
  # Service pour l'application Spring Boot
  app:
    build: .
    container_name: helping-yourself-app
    ports:
      - "8080:8080"
    env_file :
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

    # Santé de l'app
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
