services:
  # Service pour l'application Spring Boot
  app:
    build: .
    container_name: helping-yourself-app
    network_mode: "host"
    ports:
      - "8080:8080"
    env_file :
      - .env
    environment:
      - AWS.REGION=af-south-1
      - SPRING_DATASOURCE_URL=jdbc:mysql://helpingyourself.c5gs4246owpo.af-south-1.rds.amazonaws.com:3306/helpingyourself?useSSL=true&serverTimezone=UTC&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=Mkha2025!Rds#
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=prod
      - AWS_S3_REGION=af-south-1
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=valleedelauto@gmail.com
      - SPRING_MAIL_PASSWORD=bkuiqgmzkmcwntfq
      - SPRING_MAIL_FROM=no-reply@hysinternational.com
      - APP_EMAIL_FROM=no-reply@hysinternational.com


    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

    # Santé de l'app
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
