# Configuration de base

# JWT avec fallback securise
jwt.secret=VGhpc0lzQVNlY3VyZVNlZ3JldEtleUZvckpXVFNpZ25pbmcxMjM0NTY3ODkwYWJjZGVmZ2hpamtsbW5vcA==
jwt.expirationMs=86400000

spring.application.name=HelpingYourSelf

server.port=8080
server.address=0.0.0.0
# === CONFIG MYSQL ===
spring.datasource.url=jdbc:mysql://localhost:3306/helpingyourself?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=segnane


# === CONFIG JPA ===

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# File Upload Configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=500MB

# Server config
server.error.whitelabel.enabled=false
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# === AWS S3 ===
aws.s3.bucket-name=hsycompartiment
aws.s3.region=af-south-1
aws.s3.profiles-folder=profiles
aws.s3.status-folder=status_media
aws.s3.publications-folder=publications
aws.s3.messages-folder=messages
